// This file was auto-generated by ML.NET Model Builder. 
using InvoiceItemClassifierAPI.Middlewares;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;
using Serilog;

// Configure app
var builder = WebApplication.CreateBuilder(args);

// Logs
var logger = new LoggerConfiguration()
  .ReadFrom.Configuration(builder.Configuration)
  .Enrich.FromLogContext()
  .CreateLogger();
builder.Logging.ClearProviders();
builder.Logging.AddSerilog(logger);

// Middelwares
builder.Services.AddTransient<GlobalErrorHandlingMiddleware>();

builder.Services.AddPredictionEnginePool<InvoiceLine.ModelInput, InvoiceLine.ModelOutput>()
    .FromFile("InvoiceLine.zip");

builder.Services.AddControllers();

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Invoice Item Classifier API", Description = "Docs for my API", Version = "v1" });
});
var app = builder.Build();

// Middlewares
app.UseMiddleware<GlobalErrorHandlingMiddleware>();

app.UseSwagger();

app.UseSwagger();
app.UseSwaggerUI(c =>
{
    c.ConfigObject.AdditionalItems.Add("persistAuthorization", "true");
});

app.MapControllers();

app.Run();
