﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace InvoiceItemAnalyzerAPI
{
    public partial class InvoiceItemModel
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Description",outputColumnName:@"Description")      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"BusinessPartner",outputColumnName:@"BusinessPartner"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Description",@"BusinessPartner"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"ExpenseCategory",inputColumnName:@"ExpenseCategory"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastTree(new FastTreeBinaryTrainer.Options(){NumberOfLeaves=23,MinimumExampleCountPerLeaf=2,NumberOfTrees=117,MaximumBinCountPerFeature=175,FeatureFraction=0.99999999,LearningRate=0.0623166425255509,LabelColumnName=@"ExpenseCategory",FeatureColumnName=@"Features"}),labelColumnName: @"ExpenseCategory"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
